### ISSUE TITLE
stack error

### ISSUE THREAD

**Issue by diogoamore** [openearth/lisflood-fp-bmi#2]
Dear Jannis,

I have managed to compile the source code in Linux, however, there is this error showing up:

> ***************************
>  LISFLOOD-FP version 5.99.0
> ***************************
>  This is a modified version 5.9 including Basic Model Interface (BMI) compatibility
> ***************************
>  The model needs therefore be executed accordingly!
> ***************************
> *** stack smashing detected ***: <unknown> terminated
> Aborted

Have you got any clue of why that is so?

Cheers

Diogo

**Comment by ChippChapp** [comment]
Dear Diogo,

thanks for posting this issue.
I haven't seen this error before so cannot give you a detailed explanation why it occurs.
Since you see the header "LISFLOOD-FP version 5.99 and so forth", I would think that it compiled correctly but the model input files are not correct.
Could you double check of your par-file and the associated files are okay?

Hope this helps!

Cheers, Jannis

**Comment by diogoamore** [comment]
Thanks for your feedback Jannis,

I will have a thorough look at the file and if I have any further doubt I will contact you.

Many thanks

Diogo

**Comment by JannisHoch** [comment]
no feedback since, thus closed this issue.
